var list=[
["<img width='50px' src='http://www.nintendo.co.jp/n01/n64/software/nus_p_nalj/smash/flash/0222/charactericon/ness.jpg' />","豊臣　秀吉","とよとみ　ひでよし","7334","ＩＴソリューション部","TS","一般社員","n2817@ndensan.co.jp","TOYOTOMI　HIDEYOSHI"],
["<img width='50px' src='http://fgamers.saikyou.biz/image/game/ggxxac+r/sol.jpg' />","ソル","そる","1000","ギルティギア","GG","並キャラ","N1001",""],
["<img width='50px' src='http://fgamers.saikyou.biz/image/game/ggxxac+r/ky.jpg' />","カイ","かい","1001","ギルティギア","GG","並キャラ","N1002",""],
["<img width='50px' src='http://fgamers.saikyou.biz/image/game/ggxxac+r/may.jpg' />","メイ","めい","1002","ギルティギア","GG","弱キャラ","N1003",""],
["<img width='50px' src='http://fgamers.saikyou.biz/image/game/ggxxac+r/millia.jpg' />","ミリア","みりあ","1003","ギルティギア","GG","並キャラ","N1004",""],
["<img width='50px' src='http://fgamers.saikyou.biz/image/game/ggxxac+r/eddie.jpg' />","エディ","えでぃ","1004","ギルティギア","GG","強キャラ","N1005",""],
["<img width='50px' src='http://fgamers.saikyou.biz/image/game/ggxxac+r/chipp.jpg' />","チップ","ちっぷ","1005","ギルティギア","GG","並キャラ","N1006",""],
["<img width='50px' src='http://fgamers.saikyou.biz/image/game/ggxxac+r/potemkin.jpg' />","ポチョムキン","ぽちょむきん","1006","ギルティギア","GG","並キャラ","N1007",""],
["<img width='50px' src='http://fgamers.saikyou.biz/image/game/ggxxac+r/axl.jpg' />","アクセル","あくせる","1007","ギルティギア","GG","並キャラ","N1008",""],
["<img width='50px' src='http://fgamers.saikyou.biz/image/game/ggxxac+r/johnny.jpg' />","ジョニー","じょにー","1008","ギルティギア","GG","弱キャラ","N1009",""],
["<img width='50px' src='http://fgamers.saikyou.biz/image/game/ggxxac+r/jam.jpg' />","ジャム","じゃむ","1009","ギルティギア","GG","並キャラ","N1010",""],
["<img width='50px' src='http://fgamers.saikyou.biz/image/game/ggxxac+r/anji.jpg' />","闇慈","あんじ","1010","ギルティギア","GG","並キャラ","N1011",""],
["<img width='50px' src='http://fgamers.saikyou.biz/image/game/ggxxac+r/venom.jpg' />","ヴェノム","ヴぇのむ","1011","ギルティギア","GG","弱キャラ","N1012",""],
["<img width='50px' src='http://fgamers.saikyou.biz/image/game/ggxxac+r/testament.jpg' />","テスタメント","てすためんと","1012","ギルティギア","GG","並キャラ","N1013",""],
["<img width='50px' src='http://fgamers.saikyou.biz/image/game/ggxxac+r/dizzy.jpg' />","ディズィー","でぃずぃー","1013","ギルティギア","GG","並キャラ","N1014",""],
["<img width='50px' src='http://fgamers.saikyou.biz/image/game/ggxxac+r/slayer.jpg' />","スレイヤー","すれいやー","1014","ギルティギア","GG","並キャラ","N1015",""],
["<img width='50px' src='http://fgamers.saikyou.biz/image/game/ggxxac+r/ino.jpg' />","イノ","いの","1015","ギルティギア","GG","弱キャラ","N1016",""],
["<img width='50px' src='http://fgamers.saikyou.biz/image/game/ggxxac+r/zappa.jpg' />","ザッパ","ざっぱ","1016","ギルティギア","GG","強キャラ","N1017",""],
["<img width='50px' src='http://fgamers.saikyou.biz/image/game/ggxxac+r/bridget.jpg' />","ブリジット","ぶりじっと","1017","ギルティギア","GG","弱キャラ","N1018",""],
["<img width='50px' src='http://fgamers.saikyou.biz/image/game/ggxxac+r/order-sol.jpg' />","織田ソル","おだそる","1018","ギルティギア","GG","並キャラ","N1019",""],
["<img width='50px' src='http://fgamers.saikyou.biz/image/game/ggxxac+r/aba.jpg' />","アバ","あば","1019","ギルティギア","GG","並キャラ","N1020",""],
["<img width='50px' src='http://fgamers.saikyou.biz/image/game/hokuto/kenshiro.jpg' />","ケンシロウ","けんしろう","1020","北斗の拳","HK","並キャラ","N2001",""],
["<img width='50px' src='http://fgamers.saikyou.biz/image/game/hokuto/shin.jpg' />","シン","しん","1021","北斗の拳","HK","並キャラ","N2002",""],
["<img width='50px' src='http://fgamers.saikyou.biz/image/game/hokuto/thouther.jpg' />","サウザー","さうざー","1022","北斗の拳","HK","並キャラ","N2003",""],
["<img width='50px' src='http://fgamers.saikyou.biz/image/game/hokuto/rei.jpg' />","レイ","れい","1023","北斗の拳","HK","強キャラ","N2004",""],
["<img width='50px' src='http://fgamers.saikyou.biz/image/game/hokuto/jagi.jpg' />","ジャギ","じゃぎ","1024","北斗の拳","HK","弱キャラ","N2005",""],
["<img width='50px' src='http://fgamers.saikyou.biz/image/game/hokuto/toki.jpg' />","トキ","とき","1025","北斗の拳","HK","強キャラ","N2006",""],
["<img width='50px' src='http://fgamers.saikyou.biz/image/game/hokuto/raou.jpg' />","ラオウ","らおう","1026","北斗の拳","HK","並キャラ","N2007",""],
["<img width='50px' src='http://fgamers.saikyou.biz/image/game/hokuto/juda.jpg' />","ユダ","ゆだ","1027","北斗の拳","HK","並キャラ","N2008",""],
["<img width='50px' src='http://fgamers.saikyou.biz/image/game/hokuto/mamiya.jpg' />","マミヤ","まみや","1028","北斗の拳","HK","弱キャラ","N2009",""],
["<img width='50px' src='http://livedoor.blogimg.jp/aquapazza/imgs/a/f/af1de8ef.jpg' />","番長","ばんちょう","1029","ペルソナ","P4","強キャラ","N3001",""],
["<img width='50px' src='http://livedoor.blogimg.jp/aquapazza/imgs/a/f/af7acda5.jpg' />","陽介","ようすけ","1030","ペルソナ","P4","並キャラ","N3002",""],
["<img width='50px' src='http://livedoor.blogimg.jp/aquapazza/imgs/8/d/8d726ead.jpg' />","千枝","ちえ","1031","ペルソナ","P4","強キャラ","N3003",""],
["<img width='50px' src='http://livedoor.blogimg.jp/aquapazza/imgs/8/8/88e6d276.jpg' />","美鶴","みつる","1032","ペルソナ","P4","強キャラ","N3004",""],
["<img width='50px' src='http://livedoor.blogimg.jp/aquapazza/imgs/2/b/2b6cb095.jpg' />","雪子","ゆきこ","1033","ペルソナ","P4","弱キャラ","N3005",""],
["<img width='50px' src='http://livedoor.blogimg.jp/aquapazza/imgs/1/0/10312eb8.jpg' />","完二","かんじ","1034","ペルソナ","P4","並キャラ","N3006",""],
["<img width='50px' src='http://livedoor.blogimg.jp/aquapazza/imgs/a/7/a7a0966c.jpg' />","直斗","なおと","1035","ペルソナ","P4","弱キャラ","N3007",""],
["<img width='50px' src='http://livedoor.blogimg.jp/aquapazza/imgs/f/e/fe231bff.jpg' />","真田","さなだ","1036","ペルソナ","P4","並キャラ","N3008",""],
["<img width='50px' src='http://livedoor.blogimg.jp/aquapazza/imgs/a/a/aaa4b155.jpg' />","クマ","くま","1037","ペルソナ","P4","並キャラ","N3009",""],
["<img width='50px' src='http://livedoor.blogimg.jp/aquapazza/imgs/a/1/a1ecc80e.jpg' />","アイギス","あいぎす","1038","ペルソナ","P4","並キャラ","N3010",""],
["<img width='50px' src='http://livedoor.blogimg.jp/aquapazza/imgs/4/a/4a9cc04f.jpg' />","ラビリス","らびりす","1039","ペルソナ","P4","弱キャラ","N3011",""],
["<img width='50px' src='http://livedoor.blogimg.jp/aquapazza/imgs/7/6/769fba6b.jpg' />","エリザベス","えりざべす","1040","ペルソナ","P4","弱キャラ","N3012",""],
["","","","","",""]
];

var SECTIONLIST = [
["ギルティギア", "ギルティギア"],
["北斗の拳", "北斗の拳"],
["ペルソナ", "ペルソナ"],
["ＩＴソリューション部            ", "ＩＴソリューション部            "],
["所属無", ""]];

var YUKISAKILIST = [
["N1001","ソル","ギルティギア","1","戦闘中","神殿","～12:00"],
["N1002","カイ","ギルティギア","2","待機中","アアアアああああああああああああああああああああああああああああああああああああああああああああああ","テスト"],
["N1003","メイ","ギルティギア","3","","",""],
["N1004","ミリア","ギルティギア","4","","",""],
["N1005","エディ","ギルティギア","1","","",""],
["N1006","チップ","ギルティギア","1","","",""],
["N1007","ポチョムキン","ギルティギア","1","","",""],
["N1008","アクセル","ギルティギア","1","","",""],
["N1009","ジョニー","ギルティギア","1","","",""],
["N1010","ジャム","ギルティギア","1","","",""],
["N1011","闇慈","ギルティギア","1","","",""],
["N1012","ヴェノム","ギルティギア","1","","",""],
["N1013","テスタメント","ギルティギア","1","","",""],
["N1014","ディズィー","ギルティギア","1","","",""],
["N1015","スレイヤー","ギルティギア","1","","",""],
["N1016","イノ","ギルティギア","1","","",""],
["N1017","ザッパ","ギルティギア","1","","",""],
["N1018","ブリジット","ギルティギア","1","","",""],
["N1019","織田ソル","ギルティギア","1","","",""],
["N1020","アバ","ギルティギア","1","","",""],
["N2001","ケンシロウ","北斗の拳","1","","",""],
["N2002","シン","北斗の拳","1","","",""],
["N2003","サウザー","北斗の拳","1","","",""],
["N2004","レイ","北斗の拳","1","","",""],
["N2005","ジャギ","北斗の拳","1","","",""],
["N2006","トキ","北斗の拳","1","","",""],
["N2007","ラオウ","北斗の拳","1","","",""],
["N2008","ユダ","北斗の拳","1","","",""],
["N2009","マミヤ","北斗の拳","1","","",""],
["N3001","番長","ペルソナ","1","","",""],
["N3002","陽介","ペルソナ","1","","",""],
["N3003","千枝","ペルソナ","1","","",""],
["N3004","美鶴","ペルソナ","1","","",""],
["N3005","雪子","ペルソナ","1","","",""],
["N3006","完二","ペルソナ","1","","",""],
["N3007","直斗","ペルソナ","1","","",""],
["N3008","真田","ペルソナ","1","","",""],
["N3009","クマ","ペルソナ","1","","",""],
["N3010","アイギス","ペルソナ","1","","",""],
["N3011","ラビリス","ペルソナ","1","","",""],
["N3012","エリザベス","ペルソナ","1","","",""],
["N3013","シャドウ ラビリス","ペルソナ","1","","",""],
["N2817","豊臣 秀吉","ＩＴソリューション部            ","1","","",""]];